name: Simple
# From https://github.com/jcs-emacs/jcs-emacs/blob/master/.github/workflows/startup.yml

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
    - name: Install dependencies
      run: |
        apk add emacs-nox ripgrep git sqlite

    - uses: actions/checkout@v4

    - name: Creating external directories
      run: |
        mkdir -p local
        mkdir -p ~/org/roam/projects ~/.emacs.d ~/org-roam

    - name: Test startup
      run: |
        ls -l
        emacs --batch --debug-init --init-directory . --load $(pwd)/init.el
